sudo: false

language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.2
  - 1.9.4
  - 1.10.0
otp_release:
  - 18.3
  - 19.3
  - 20.3
  - 21.3
  - 22.2

matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.3
    - elixir: 1.3.4
      otp_release: 21.3
    - elixir: 1.3.4
      otp_release: 22.2
    - elixir: 1.4.5
      otp_release: 21.3
    - elixir: 1.4.5
      otp_release: 22.2
    - elixir: 1.5.3
      otp_release: 21.3
    - elixir: 1.5.3
      otp_release: 22.2
    - elixir: 1.6.6
      otp_release: 18.3
    - elixir: 1.6.6
      otp_release: 22.2
    - elixir: 1.7.4
      otp_release: 18.3
    - elixir: 1.8.2
      otp_release: 18.3
    - elixir: 1.8.2
      otp_release: 19.3
    - elixir: 1.9.4
      otp_release: 18.3
    - elixir: 1.9.4
      otp_release: 19.3
    - elixir: 1.10.0
      otp_release: 18.3
    - elixir: 1.10.0
      otp_release: 19.3
    - elixir: 1.10.0
      otp_release: 20.3
